"""
Django settings for staff_assessment project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # 如果没有安装 python-dotenv，跳过加载


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Local apps
    'users',
    'core',
    'analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# 自定义认证后端，支持使用工号或用户名登录
AUTHENTICATION_BACKENDS = [
    'users.auth_backends.JobNumberBackend',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CSRF 信任的域名（HTTPS 反向代理必须配置）
CSRF_TRUSTED_ORIGINS = [
    'https://dofuns.cn',
    'https://www.dofuns.cn',
]

# 告诉 Django 请求来自 HTTPS 反向代理
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 让 Django 正确处理反向代理的 Host 头
USE_X_FORWARDED_HOST = True

# Assessment System Settings
ASSESSMENT_SETTINGS = {
    # 能力画像更新权重配置
    'CAPABILITY_UPDATE_WEIGHT_OLD': 0.7,
    'CAPABILITY_UPDATE_WEIGHT_NEW': 0.3,
    # 考试题目数量配置
    'DEFAULT_EXAM_QUESTION_COUNT': 10,
    # 智能组卷策略比例
    'WEAK_TAG_RATIO': 0.5,    # 弱项强化
    'NEW_QUESTION_RATIO': 0.5, # 新题探索
    # 能力阈值
    'WEAK_CAPABILITY_THRESHOLD': 60,
    # 排除时间（小时）
    'EXCLUDE_RECENT_HOURS': 1,
}

# AI 评分配置
AI_GRADING_SETTINGS = {
    'ENABLED': True,  # 是否启用AI评分
    'API_KEY': os.environ.get('DEEPSEEK_API_KEY', ''),  # AI服务的API密钥，从环境变量读取
    'MODEL_NAME': 'deepseek-chat',  # 使用的模型名称
    'BASE_URL': 'https://api.deepseek.com/v1',  # API基础URL
    'MAX_RETRIES': 3,  # 最大重试次数
    'TIMEOUT': 10,  # 请求超时时间（秒）
    'PROMPT_TEMPLATE': """
请根据以下信息对主观题进行评分：

题目：{question}
参考答案：{reference_answer}
用户答案：{user_answer}

请根据用户答案与参考答案的匹配程度给出0-100分的评分，其中：
- 90-100分：答案完整准确，完全符合要求
- 80-89分：答案基本正确，稍有不足
- 70-79分：答案部分正确，有一定理解
- 60-69分：答案不够准确，但有一定相关性
- 0-59分：答案错误或完全不符合要求

请只返回一个0-100之间的数字分数，不要返回其他文字。
""",
    'FALLBACK_SCORE': 60,  # AI调用失败时的默认分数
}