# Generated by Django 4.2.9 on 2025-11-28 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('description', models.TextField(blank=True, verbose_name='资料描述')),
                ('material_type', models.CharField(choices=[('document', '文档资料'), ('video', '视频教程'), ('exercise', '练习题'), ('other', '其他')], default='document', max_length=20, verbose_name='资料类型')),
                ('url', models.URLField(blank=True, verbose_name='资料链接')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('tags', models.ManyToManyField(blank=True, related_name='training_materials', to='core.tag', verbose_name='关联标签')),
            ],
            options={
                'verbose_name': '培训资料',
                'verbose_name_plural': '培训资料',
                'db_table': 'training_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mastery_level', models.FloatField(default=50.0, help_text='0-100，数值越高表示掌握程度越好', verbose_name='掌握度评分')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_profiles', to='core.tag', verbose_name='关联标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_profiles', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '能力画像',
                'verbose_name_plural': '能力画像',
                'db_table': 'capability_profiles',
                'ordering': ['user', 'tag'],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
