# Generated by Django 4.2.9 on 2025-11-28 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='智能考核试卷', max_length=200, verbose_name='试卷标题')),
                ('total_score', models.FloatField(default=100.0, verbose_name='试卷总分')),
                ('score_obtained', models.FloatField(blank=True, null=True, verbose_name='实际得分')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='not_started', max_length=20, verbose_name='试卷状态')),
                ('generation_reason', models.CharField(choices=[('daily_practice', '日常练习'), ('error_review', '错题回顾'), ('mandatory_assessment', '强制考核')], default='daily_practice', max_length=30, verbose_name='生成原因')),
                ('time_limit', models.PositiveIntegerField(default=1800, verbose_name='考试时限（秒）')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考试试卷',
                'verbose_name_plural': '考试试卷',
                'db_table': 'exam_papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('category', models.CharField(choices=[('position', '岗位类'), ('emergency', '应急类'), ('comprehensive', '综合能力类')], default='position', max_length=20, verbose_name='标签分类')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='题目题干')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('true_false', '判断题')], default='single', max_length=20, verbose_name='题目类型')),
                ('options', models.JSONField(help_text='JSON格式，示例: [{"key": "A", "text": "选项内容"}]', verbose_name='选项列表')),
                ('correct_answer', models.CharField(help_text='单选题填字母，多选题用逗号分隔，判断题填True/False', max_length=50, verbose_name='正确答案')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1-5，数字越大难度越高', verbose_name='难度系数')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('tags', models.ManyToManyField(related_name='questions', to='core.tag', verbose_name='关联标签')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_answer', models.CharField(blank=True, max_length=100, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score_gained', models.FloatField(default=0.0, verbose_name='得分')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='答题耗时（秒）')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='core.exampaper', verbose_name='归属试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='core.question', verbose_name='对应题目')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'db_table': 'exam_records',
                'ordering': ['paper', 'id'],
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
