# Generated by Django 4.2.27 on 2025-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251211_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('role', '职位类'), ('position', '岗位类'), ('emergency', '应急类'), ('comprehensive', '综合能力类')], default='position', max_length=20, verbose_name='标签分类'),
        ),
    ]
